evalsoc: add crypto(risc-v k extension) case
Nuclei-Software/nuclei-board-labs pull request #23
Opened 2023-12-25 06:21 UTC by surez-ok

add crypto(risc-v k extension) case

2023-12-25 10:27 UTC, fanghuaqi requested changes
看了下需要做很多细节的变更：

1. Makefile, npk.yml 和 文档中的 CORE/ARCH_EXT请务必保持一致
2. 不必要的 .gitignore 不要提交进来
3. npk.yml中很多写法都是错的，且和Makefile不一致
4. 头文件include很多都是相对路径 `../` 这样的 ，请改掉
5. 文档里面很弱，要修正补充数据

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/README.md
> +
Please list all the cases supported by us.

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/README.md
> +# require NX900FD with k extension bitstream
This is not correct, your Makefile default is n300fd with bp extension.

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/aes/npk.yml
> +      condition: $( contains(${nuclei_core}, "x"))
nuclei_core怎么会有x字符？

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/aes/reference/aes_dec.c
> +#include "../api_aes.h"
不要用这种相对路径，把头文件的PATH 加到include路径下

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/aes/reference/aes_enc.c
> +#include "../api_aes_ref.h"
同上

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/aes/npk.yml
> +  - type: gcc
不要用 gcc这样。要换成 common

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/aes/npk.yml
> +      condition: $( !contains(${nuclei_core}, "x"))
这里写错了？

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/aes/test_block_aes.c
> +#include "../share/util.h"
如上，include不要这样写

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/npk.yml
> +## Package Base Information
怎么这么多npk.yml. 你这里就一个入口的话，就写一个就行了。

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/npk.yml
> +    value: -O3 -D__ZSCRYPTO -DRVINTRIN_EMULATE=1
？？？？ 这个不需要吧，这个是用C仿真intrinsic才行

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/npk.yml
> +    value: nx900fd
这里和makefile里面不一致

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/npk.yml
> +    - path: ["${crypto_case}/*.c", "${crypto_case}/*.h", "${crypto_case}/zscrypto_rv64", "${crypto_case}/reference", "share"]
这里 如果是 区分 32和64的话，只需要把不一样的单独框起来

2023-12-25 10:27 UTC, fanghuaqi commented on evalsoc/crypto_examples/sha256/Makefile
> +NUCLEI_SDK_ROOT = ../../../..
注意看看 这里路径放在SDK是否可以正常build，就是 sdk/board_labs 这样的路径。其他的也要检查。

2024-01-05 05:11 UTC, fanghuaqi commented
@surez-ok Please update it when you are free

2024-01-08 07:50 UTC, closed without merging

2024-01-08 07:52 UTC, surez-ok commented
OK, I will fix it